# Generated by Django 5.1.4 on 2026-02-15 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('sugarcane', 'Sugarcane'), ('maize', 'Maize'), ('beans', 'Beans'), ('vegetables', 'Vegetables'), ('other', 'Other')], max_length=50)),
                ('crop_variety', models.CharField(blank=True, help_text='Specific variety name', max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(help_text='Estimated harvest date')),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('area_planted_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted/Growing'), ('harvested', 'Harvested'), ('failed', 'Failed/Lost')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Farm name or location', max_length=200)),
                ('size_acres', models.DecimalField(decimal_places=2, help_text='Size in acres', max_digits=8)),
                ('location', models.CharField(blank=True, help_text='Address or GPS coordinates', max_length=300)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], default='paid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crops.cropseason')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CropInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('seeds', 'Seeds/Seedlings'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('water', 'Irrigation Water'), ('labor', 'Labor'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(help_text='Brand/name of product', max_length=200)),
                ('quantity', models.CharField(help_text='e.g., 50 kg, 10 liters, 5 days', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='crops.cropseason')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='cropseason',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='crops.farm'),
        ),
    ]
