# Generated by Django 5.1.4 on 2026-02-15 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'January 2025' or 'Maize Season 2025'", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('milk_sale', 'Milk Sale'), ('crop_sale', 'Crop Sale'), ('animal_sale', 'Animal Sale'), ('other_income', 'Other Income'), ('feed', 'Animal Feed'), ('veterinary', 'Veterinary/Health'), ('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('labor', 'Labor/Wages'), ('transport', 'Transport'), ('equipment', 'Equipment/Tools'), ('utilities', 'Utilities'), ('other_expense', 'Other Expense')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=300)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('credit', 'Credit/Pending')], default='cash', max_length=20)),
                ('party_name', models.CharField(blank=True, help_text='Buyer/Seller/Supplier name', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Receipt/Invoice number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
