# Generated by Django 5.1.4 on 2026-02-15 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('sheep', 'Sheep')], max_length=10)),
                ('tag_number', models.CharField(help_text='Unique ID/Tag', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name', max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_acquired', models.DateField(default=django.utils.timezone.now)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('mother_tag', models.CharField(blank=True, help_text="Mother's tag number", max_length=50)),
                ('father_tag', models.CharField(blank=True, help_text="Father's tag number", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_type', models.CharField(help_text='e.g., Hay, Concentrate, Silage', max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Quantity in kg', max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('checkup', 'Checkup'), ('injury', 'Injury'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='What was done/observed')),
                ('veterinarian', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_due_date', models.DateField(blank=True, help_text='Next vaccination/checkup date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='dairy.animal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField(default=django.utils.timezone.now)),
                ('bull_tag', models.CharField(blank=True, help_text='Bull/Ram tag number', max_length=50)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('bred', 'Recently Bred'), ('confirmed', 'Pregnancy Confirmed'), ('due_soon', 'Due Soon'), ('delivered', 'Delivered'), ('failed', 'Failed/Aborted')], default='bred', max_length=20)),
                ('offspring_count', models.IntegerField(default=0, help_text='Number of calves/lambs')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='dairy.animal')),
            ],
            options={
                'ordering': ['-breeding_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('morning_liters', models.DecimalField(decimal_places=2, default=0, help_text='Morning milking', max_digits=6)),
                ('evening_liters', models.DecimalField(decimal_places=2, default=0, help_text='Evening milking', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='dairy.animal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('animal', 'date')},
            },
        ),
    ]
